{% set name = "decli" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decli-{{ version }}.tar.gz
  sha256: 2915a55525ef2b1a0ce88b8ccba62ac22df5b6ff3ed2094448e0f951f08e7ba5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - decli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/decli/
  summary: Minimal, easy-to-use, declarative cli tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - dsangillo
